### ISSUE TITLE
Links to docs are not clickable

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#2274]
Go to https://rdf4j.org/documentation/ on an iPhone (haven’t tested android). None of the links are clickable!

**Comment by hmottestad** [comment]
@jeenbroekstra @barthanssens could you guys test this?

**Comment by jeenbroekstra** [comment]
Same on Android. Peculiar - I am not aware that we're doing anything special for these links, they're just regular html anchors AFAIK.

**Comment by jeenbroekstra** [comment]
It doesn't seem specific to the mobile version of the site either. If I switch to the desktop version on my phone, those links are still not clickable.

**Comment by jeenbroekstra** [comment]
It appears to be specific to that particular page, links on other pages (including subsections, e.g. https://rdf4j.org/documentation/programming/) work fine. Something in the CSS stuff I put in there to make the boxes and orange headers perhaps.

I've just noticed that I can reproduce the problem using Firefox on my computer, running Responsive Design Mode. I'm a little rusty on (mobile) web design but I'll and take a closer look.

**Comment by jeenbroekstra** [comment]
Fix deployed, and confirmed it works on Android (I had to clean my browser cache though). @hmottestad can you check on iphone?

**Comment by hmottestad** [comment]
It looks better, but there is still a problem on desktop if I set the width just right. Width between ~600px and ~950px.

**Comment by jeenbroekstra** [comment]
What problem are you seeing?

**Comment by hmottestad** [comment]
Same problem.

**Comment by hmottestad** [comment]
@jeenbroekstra can we revert to the old template for that page maybe?
